#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${ENV_FILE:-$REPO_ROOT/.env}"

banner "CVAT deployment"

# ── Stage 1: Docker daemon ────────────────────────────────────────────────
stage "Docker Desktop"
say "CVAT runs in Docker, so the daemon must be up first."
if docker info >/dev/null 2>&1; then
  note "Docker daemon is running."
else
  step "Start Docker Desktop from the Start menu or taskbar and wait for the whale icon to go steady."
  pause "Press Enter once Docker Desktop reports it is running."
  if ! docker info >/dev/null 2>&1; then
    warn "Docker is still unreachable. Restart Docker Desktop, then re-run this wizard."
    exit 1
  fi
fi

# ── Stage 2: CVAT source ──────────────────────────────────────────────────
stage "CVAT source"
ask CVAT_REPO_DIR "Directory to clone CVAT into [${HOME}/cvat]:"
if [[ -z "$CVAT_REPO_DIR" ]]; then
  CVAT_REPO_DIR="$HOME/cvat"
fi
if [[ -d "$CVAT_REPO_DIR/.git" ]]; then
  note "CVAT is already cloned at $CVAT_REPO_DIR."
else
  note "Cloning https://github.com/cvat-ai/cvat ..."
  git clone --depth 1 https://github.com/cvat-ai/cvat.git "$CVAT_REPO_DIR"
fi
write_env CVAT_REPO_DIR "$CVAT_REPO_DIR"
write_env CVAT_URL "http://localhost:8080"

# ── Stage 3: Start CVAT ───────────────────────────────────────────────────
stage "Start CVAT"
note "Bringing up the CVAT stack with docker compose (first run downloads images and can take a while)."
(
  cd "$CVAT_REPO_DIR"
  docker compose -f docker-compose.yml up -d
)
say "Waiting for CVAT at http://localhost:8080 ..."
reachable=0
for _ in $(seq 1 60); do
  if curl -fsS http://localhost:8080 >/dev/null 2>&1; then reachable=1; break; fi
  sleep 5
done
if [[ "$reachable" -ne 1 ]]; then
  warn "CVAT did not become reachable within 5 minutes. Check logs with:"
  warn "  cd $CVAT_REPO_DIR && docker compose logs -f"
  exit 1
fi
note "CVAT is reachable."

# ── Stage 4: Admin account ────────────────────────────────────────────────
stage "Admin account"
say "CVAT needs an admin login. This wizard creates it for you inside the server container."
ask CVAT_ADMIN_USER "Admin username:"
ask CVAT_ADMIN_EMAIL "Admin email:"
ask_secret CVAT_ADMIN_PASSWORD "Admin password (hidden):"
if [[ -z "$CVAT_ADMIN_USER" || -z "$CVAT_ADMIN_PASSWORD" ]]; then
  warn "Username and password are required."
  exit 1
fi
write_env CVAT_ADMIN_USER "$CVAT_ADMIN_USER"
write_env CVAT_ADMIN_EMAIL "$CVAT_ADMIN_EMAIL"
write_env CVAT_ADMIN_PASSWORD "$CVAT_ADMIN_PASSWORD"
if (
  cd "$CVAT_REPO_DIR"
  docker compose exec -T cvat_server bash -c \
    "DJANGO_SUPERUSER_USERNAME='$CVAT_ADMIN_USER' DJANGO_SUPERUSER_EMAIL='$CVAT_ADMIN_EMAIL' DJANGO_SUPERUSER_PASSWORD='$CVAT_ADMIN_PASSWORD' python3 manage.py createsuperuser --noinput"
); then
  note "Superuser created."
else
  warn "createsuperuser failed. If the user already exists, that is fine - continue."
fi
note "The admin password is stored in $ENV_FILE; change it in CVAT after logging in."

# ── Stage 5: Log in ───────────────────────────────────────────────────────
stage "Log in to CVAT"
open_url "http://localhost:8080"
step "If you are not already signed in, the login page shows a Username field and a Password field."
step "Type $CVAT_ADMIN_USER as the username."
step "Type the admin password you set in the previous stage."
step "Click 'Sign in'."
say "You should land on the Tasks page. If a tour/onboarding dialog appears, close it."
pause "Press Enter once you are logged in."

# ── Stage 6: Project and labels ───────────────────────────────────────────
stage "Create project and import labels"
say "Create the CVAT project that the annotation guide refers to, and load the label schema into it."
open_url "http://localhost:8080/projects"
step "On the Projects page, click the 'Create project' button."
step "In the 'Name' field, type: suture-quality-pilot"
say "In recent CVAT versions the create dialog has no label import. If you see a label area with an import/upload icon, import $REPO_ROOT/configs/cvat_labels.json there; otherwise leave labels empty."
step "Click 'Submit' to save the project."
step "Click the project name 'suture-quality-pilot' in the projects list to open it."
step "Open the 'Labels' tab (or Labels section) on the project page."
step "Use the import/upload control there and select: $REPO_ROOT/configs/cvat_labels.json"
say "The 11 labels (wound_pad, needle, thread, entry_point, exit_point, stitch, knot, and the four event labels) should appear with their attributes."
pause "Press Enter once the project exists and all 11 labels are listed."

# ── Stage 7: Annotation tasks from frames ─────────────────────────────────
stage "Create annotation tasks"
say "Create one CVAT task per source video so annotations stay traceable to a video and timestamp."
say "Each task is an IMAGE task built from the extracted frames. Tracks still interpolate across image sequences, so key frames remain the only frames you must draw on."
for frame_dir in "$REPO_ROOT"/data/frames/*/; do
  video_id="$(basename "$frame_dir")"
  step "Create task '$video_id': open the Tasks page, click 'Create task', name it '$video_id'."
  step "  In 'Project', select 'suture-quality-pilot'."
  step "  In 'Files', use 'Local files' and add the images from: $frame_dir"
  step "  Click 'Submit' and wait for the task to finish creating (uploads can take a while for large folders)."
done
say "If a single video's task is too large to upload comfortably, create several tasks per video (e.g. frame_000001-frame_001000) and name them '$video_id-part1', '$video_id-part2', and so on."
pause "Press Enter once the tasks are created."

finish